GET http://localhost:3000/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphaSIsImlhdCI6MTY4NTg2NzM5OH0.pnz3Y5-RxJV7rAsiqRAtLbZHg7CFmEIRemlx7-SrYIA


###

# Update Post
PUT http://localhost:3000/posts/647c4b9f560a9d8da43efd4b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphaSIsImlhdCI6MTY4NTg2NzI4Mn0.tWAEDFDLa4T8IRL28e78xFCwuKpkgijK2sLWuz3wxHY

{
  "username": "jai",
  "title": "Updated Post Title anukriti"

}


###

# Delete Post
DELETE http://localhost:3000/posts/647b6520560a9d8da43efd46
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphaSIsImlhdCI6MTY4NTg2NzI4Mn0.tWAEDFDLa4T8IRL28e78xFCwuKpkgijK2sLWuz3wxHY


###

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphaSIsImlhdCI6MTY4NTU1MzkxNX0.Lwfwi667M-5EjOeH4xubmHhtH3f_VZD687NYuB9nVIU"
}

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjg1MTI0MzYxfQ.COE-YHXcI6m3AqlFOhVngxuIQJi10fMd7C_DPo5X3xc"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Jai",
  "password": "passwordjai"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "Jai",
  "password": "passwordjai"
}